### ISSUE TITLE
loc_name bug in ps_wrapper?

### ISSUE THREAD

**Issue by adampbeardsley** [miguelfmorales/eppsilon#1]
I'm experiencing a strange bug when I run ps_wrapper on the mit cluster. It only happens once in a while, and I'm having a hard time recreating it.
The symptom:
Sometimes I get the following error when I run ps_wrapper (via ps_script on the mit cluster):
`
% Variable is undefined: LOC_NAME.
% Execution halted at: PS_WRAPPER         36
   /nfs/eor-00/h1/beards/MWA/IDL_code/PS/ps_wrappers/ps_wrapper.pro
%                      MIT_PS_JOB         16
   /nfs/eor-00/h1/beards/MWA/IDL_code/PS/ps_wrappers/mit_ps_job.pro
%                      $MAIN$ 
`
I've tried walking through the relevant lines of code in ps_wrapper from an interactive shell, and I can't seem to reproduce the problem. So far I've seen the error appear when run on eor-08, eor-09, and eor-11. I've also seen the wrapper successfully run on  eor-02 and eor-08. Since eor-08 ran successfully and with error, I'm not sure it's node specific.

Has anyone else seen this? Or have any ideas what's going on?

**Comment by patti** [comment]
I ran into this too. I'm not sure what's going on either. I hard-coded `loc_name='mit'` at line 36 to hack around it.

**Comment by bhazelton** [comment]
Nichole first noticed this and I can't reproduce it or explain it either,
but I added the loc_name keyword to give you a way to get around it as
Patti describes. Sorry!

**Comment by adampbeardsley** [comment]
Gotcha. I went ahead and added the loc_name option in the mit_ps_job.pro script, which is specific to mit anyway.
